# Site settings
title: Scazzo
description: Grande Giove!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scazzo.github.io" # the base hostname & protocol for your site
github_username: scazzo
paginate: 5
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
